version: '3.9'

services:
  user-service:
    image: phantomrogue88/user-service:latest
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      DB_URL: "$DB_URL"
      DB_USERNAME: "$DB_USERNAME"
      DB_PASSWORD: "$DB_PASSWORD"
      JWT_SECRET: "$JWT_SECRET"

  product-service:
    image: phantomrogue88/product-service:latest
    container_name: product-service
    ports:
      - "8083:8083"
    environment:
      DB_URL: "$DB_URL"
      DB_USERNAME: "$DB_USERNAME"
      DB_PASSWORD: "$DB_PASSWORD"

  cart-service:
    image: phantomrogue88/cart-service:latest
    container_name: cart-service
    ports:
      - "8081:8081"
    environment:
      DB_URL: "$DB_URL"
      DB_USERNAME: "$DB_USERNAME"
      DB_PASSWORD: "$DB_PASSWORD"
      JWT_SECRET: "$JWT_SECRET"
    depends_on:
      - user-service
      - product-service

  order-service:
    image: phantomrogue88/order-service:latest
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      DB_URL: "$DB_URL"
      DB_USERNAME: "$DB_USERNAME"
      DB_PASSWORD: "$DB_PASSWORD"
      JWT_SECRET: "$JWT_SECRET"
    depends_on:
      - cart-service

  orbit-frontend:
    image: phantomrogue88/orbit-app:latest
    container_name: orbit-frontend
    ports:
      - "3000:80"
    depends_on:
      - user-service
      - product-service
      - cart-service
      - order-service
