# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: ORBIT - Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build all modules
      run: mvn -B clean install -DskipTests

    - name: Build & push Product Service image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: phantomrogue88/product-service
        tags: v1, latest
        registry: docker.io
        dockerfile: services/product-service/Dockerfile
        directory: services/product-service
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push User Service image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: phantomrogue88/user-service
        tags: v1, latest
        registry: docker.io
        dockerfile: services/user-service/Dockerfile
        directory: services/user-service
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push Order Service image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: phantomrogue88/order-service
        tags: v1, latest
        registry: docker.io
        dockerfile: services/order-service/Dockerfile
        directory: services/order-service
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & push Cart Service image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: phantomrogue88/cart-service
        tags: v1, latest
        registry: docker.io
        dockerfile: services/cart-service/Dockerfile
        directory: services/cart-service
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Copy docker-compose.yml to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "docker-compose.yml"
        target: "/home/ubuntu/orbit/"

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/orbit
          source /etc/environment
          sudo docker compose pull
          sudo docker compose up -d --remove-orphans

